### ISSUE TITLE
why used a fixed SHA tag ?

### ISSUE THREAD

**Issue by lucwastiaux** [potz/docker-ergodox-ez-compiler#2] opened 2016-07-12 14:37 UTC
Your image could be more functional if you used the latest features of the QMK firmware, why stay stuck on a particular revision ?

**Comment by potz** [comment] 2016-07-12 15:35
I was not aware of a new version but haven't used this in a while tbh. I'd be happy to accept a pull request.

**Comment by potz** [comment] 2016-07-12 15:37
Oh I see you mean the hard coded sha in the image. I was thinking  to improve reproducibility I guess, but I didn't think it through.

**Comment by potz** [comment] 2016-09-15 16:36
Hi @lucwastiaux, sorry it took me so long to respond. 

I am updating the image to pull from the latest commit and making the necessary amends so the build works. However, I will keep a hard-coded reference to this new SHA in the Dockerfile. After careful consideration I think it's the best option to keep the image reproducible and also to prevent build failures.

We cannot know beforehand when new dependencies will be introduced in the firmware build process or say, if folders names will change in the original repo. Both things actually happened since [ec4428](/jackhumbert/qmk_firmware/commit/ec4428) (in this latest commit [a25835](/jackhumbert/qmk_firmware/commit/a25835) the folder `/firmware/keyboard/ergodox_ez` was renamed to `/firmware/keyboards/ergodox/ez` and new dependencies were added (`dfu-programmer`), also the default `keymap.c` changed). If I had just pulled directly from the master branch the image would stop working at some point back in time. Having a SHA fixed guarantees a working image, even if outdated.

Thank you for opening this issue and point out that it was indeed very outdated, I'm using the version now. I agree that it's good to have the most up-to-date version but really the best I can do about it is to update the SHA from time to time and see if there are any changes required to the build process.

**Closed by potz** 2016-09-15 16:36 UTC
